### ISSUE TITLE
Smart text diffs

### ISSUE THREAD

**Issue by danielgtaylor** [btd/mocha-better-spec-reporter#2]
It would be nice to get smart multiline text diffs like Mocha's default spec reporter does now. Example with `mocha-better-spec-reporter`:

<img width="550" alt="screen shot 2015-09-11 at 11 07 28" src="https://cloud.githubusercontent.com/assets/106826/9811096/71c3a7c8-5875-11e5-81e7-a372fd423352.png">

Example with Mocha's default reporter:

<img width="553" alt="screen shot 2015-09-11 at 11 07 39" src="https://cloud.githubusercontent.com/assets/106826/9811105/7866e7f2-5875-11e5-847b-23497eb26bde.png">

Any chance you could port that over? I prefer this project because of the included file snippets. Thanks!

**Comment by btd** [comment]
It looks like some sort of custom formatting applied. Could you add more details, please? It looks youp text contains some sort of API description. Is it right?

**Comment by btd** [comment]
I actually looked on fresh mocha and I do not see anything that do formatting like you pointed. I definitely need more details. What mocha version, run arms. Anything else?

**Comment by danielgtaylor** [comment]
@btd mocha version is 2.3.2. Here is a sample test case:

File: test.js
```js
var expect = require('chai').expect;

it('will fail', function () {
  expect('one\ntwo\nthree\nfour\n').to.deep.equal('one\ntwo:2\nthree\n');
});
```

Run: `mocha -R spec`
<img width="549" alt="screen shot 2015-09-11 at 12 35 23" src="https://cloud.githubusercontent.com/assets/106826/9812952/a519a1ca-5881-11e5-83a0-c8f4d38498e9.png">

Run: `mocha -R mocha-better-spec-reporter`
<img width="549" alt="screen shot 2015-09-11 at 12 35 36" src="https://cloud.githubusercontent.com/assets/106826/9812968/bf1dc8bc-5881-11e5-884b-1124536c69f4.png">

**Comment by btd** [comment]
Got it. You just mean to do not escape new lines. I cannot do this right now. Because I am on vacation right now. I will do at Monday or Sunday.

**Comment by danielgtaylor** [comment]
@btd thanks and no rush! Enjoy your vacation :smile:

**Comment by btd** [comment]
Hi again. Try 2.1.2 should look better.

**Comment by danielgtaylor** [comment]
@btd this is working much better, thanks for the fix!
